---
- name: Install sensor client for raspberry pi
  hosts: all
  vars:
    ansible_ssh_user: pi
  tasks:
  - name: Define wifi
    become: yes
    template:
      src: templates/wpa_supplicant.conf.j2
      dest: /etc/wpa_supplicant/wpa_supplicant.conf
  - name: Define ip
    become: yes
    template:
      src: templates/dhcpcd.conf.j2
      dest: /etc/dhcpcd.conf
  - name: unblock wlan0 interface (not always needed)
    become: yes
    command: rfkill unblock all
  - name: activate wlan0 interface
    become: yes
    command: ifconfig wlan0 up
  - name: Reboot Raspberry
    become: yes
    command: /sbin/shutdown -r 0
    async: 0
    poll: 0
    ignore_errors: true
...
