---
- name: Add authorized keys
  authorized_key:
    user: pi
    state: present
    key: "{{ item }}"
  with_items:
    - https://github.com/AdrianFarmadin.keys
    - https://github.com/awagenhoffer.keys
    - https://github.com/b0x1.keys
    - https://github.com/eerofeev.keys
    - https://github.com/ErhardSiegl.keys
    - https://github.com/evelynpirklbauer.keys
    - https://github.com/gattma.keys
    - https://github.com/hwirnsberger.keys
    - https://github.com/kwimmergit.keys
    - https://github.com/mbrandm.keys
    - https://github.com/Montecito.keys
    - https://github.com/sjutz.keys
    - https://github.com/steirer2.keys
    - https://github.com/WernerGepardec.keys
    - https://github.com/wiesell.keys
...