---
- name: Install sensor client for raspberry pi
  hosts: pi
  vars:
    ansible_ssh_user: pi
  tasks:
  - name: Enable hardware SPI
    become: yes
    lineinfile: 
      dest: /boot/config.txt
      regexp: dtparam=spi=on
      line: dtparam=spi=on
      state: present
    notify:
      - restart
  - meta: flush_handlers
  - name: Update cache and upgrade
    become: yes
    apt:
      update_cache: yes
      upgrade: yes
  - name: Install python dependencies
    become: yes
    apt: name={{item}} state=installed
    with_items:
        - build-essential
        - python-pip
        - python-dev
        - python-smbus
  - name: Install git-core
    become: yes
    apt:
      name: git-core
      state: present
  - name: Checkout Hogarama
    git:
      repo: 'https://github.com/Gepardec/Hogarama.git'
      dest: "{{ ansible_env.HOME}}/Hogarama"
      force: yes
  - name: Checkout Adafruit_Python_GPIO
    git:
      repo: 'https://github.com/adafruit/Adafruit_Python_GPIO.git'
      dest: "{{ ansible_env.HOME}}/Adafruit_Python_GPIO"
  - name: Build Adafruit_Python_GPIO
    become: yes
    command: python setup.py install
    args:
      chdir: "{{ ansible_env.HOME}}/Adafruit_Python_GPIO"
    run_once: true
  - name: Checkout Adafruit_Python_MCP3008
    git:
      repo: 'https://github.com/adafruit/Adafruit_Python_MCP3008.git'
      dest: "{{ ansible_env.HOME}}/Adafruit_Python_MCP3008"
  - name: Build Adafruit_Python_MCP3008
    become: yes
    command: python setup.py install
    args:
      chdir: "{{ ansible_env.HOME}}/Adafruit_Python_MCP3008"
    run_once: true
  handlers:
  - name: Restart Pi
    become: yes
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true
    listen: restart
  - name: Wait for Pi to boot
    local_action: wait_for host={{ inventory_hostname }} 
      state=started 
      port=22 
      delay=80 
      timeout=300 
      connect_timeout=15
    listen: restart
...
